apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: creditprocessor-dev
    creationTimestam: null
  displayName: creditprocessor - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: creditprocessor-stage
    creationTimestam: null
  displayName: creditprocessor - Stage
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: creditprocessor-prod
    creationTimestam: null
  displayName: creditprocessor - Prod
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: creditprocessor-build
    creationTimestam: null
  displayName: creditprocessor - Build